listener {
    timeout = 295
    on-timeout = notify-send "⚡ Mana Low" "Reducing visual effects to conserve magic."
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && hyprlock


}
listener{
    timeout = 300
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' &&  brightnessctl -r


  }



listener {
    timeout = 300
    on-resume = notify-send "👀 Welcome Back" "I definitely wasn't watching."
}
